import type { EmotionalPattern } from '@/types'

export const PATTERNS: EmotionalPattern[] = [
  // HUMOR
  {
    id: 'laughter',
    name: '笑い',
    category: 'humor',
    trajectoryType: 'Type I',
    description: '安全な意外性が、意味として急速に再統合されたときの解放感',
    dynamics: 'ΔS↑ C↑ B↑',
    coreRule: 'オチで意味が一瞬で再統合される。安全・軽快さを保ち、説明しない。',
  },
  {
    id: 'tsukkomi',
    name: 'ツッコミの快感',
    category: 'humor',
    trajectoryType: 'Type I',
    description: 'ボケとツッコミの二拍子で生まれる即時の解放感',
    dynamics: 'ΔS↑ C↑↑ B↑',
    coreRule: '設定→即時修正の二行構造。修正がスッキリ感を生む。テンポが命。',
  },
  {
    id: 'fukusen',
    name: '伏線回収の快感',
    category: 'humor',
    trajectoryType: 'Type II',
    description: '冒頭で見落とした何かが、後から強い意味を獲得する驚きと満足',
    dynamics: 'ΔS↑ C遅→急 E↓',
    coreRule: '序盤に目立たない伏線を埋め込み、終盤で静かに回収する。説明しない。',
  },
  {
    id: 'fukai_joke',
    name: '不快な冗談',
    category: 'humor',
    trajectoryType: 'Type I',
    description: '笑いの構造は持つが、安全性（B）が閾値を下回り不快感が残る',
    dynamics: 'ΔS↑ C↑ B↓',
    coreRule: '笑いの形式を使いながら、安全・安心の感覚を壊す。居心地の悪さを残す。',
  },
  {
    id: 'imi_fumei',
    name: '意味不明なギャグ',
    category: 'humor',
    trajectoryType: 'Type III',
    description: '高い予測不能性と低い意味回収が生む不思議な可笑しさ',
    dynamics: 'E↑↑ C↓',
    coreRule: '意味を回収しない。シュールで脈絡がなく、だが不快でもない。「え？」で終わる。',
  },
  // EMOTION
  {
    id: 'kandou',
    name: '感動',
    category: 'emotion',
    trajectoryType: 'Type IV',
    description: '具体的な積み重ねが臨界点に達し、感情が溢れ出す瞬間',
    dynamics: 'S持続 ΔS↑ I↑ V↑',
    coreRule: '具体的な細部を長く積み上げる。感情の放出は説明せず、行動で示す。',
  },
  {
    id: 'catharsis',
    name: 'カタルシス',
    category: 'emotion',
    trajectoryType: 'Type IV',
    description: '長く抑えられたものが外向きに爆発する解放の瞬間',
    dynamics: 'ΔS↑↑ A↑↑ V↑↑',
    coreRule: '叫ぶ・崩れる・抱き合う。内省ではなく外向きの爆発。抑圧期間が長いほど効果的。',
  },
  {
    id: 'nakeru',
    name: '泣けるドラマ',
    category: 'emotion',
    trajectoryType: 'Type IV',
    description: '解決はあるが、取り戻せない何かが残る苦甘い余韻',
    dynamics: 'S持続 ΔS↑ I↑↑ 余韻',
    coreRule: '解決を示しながら、失われたものも明示する。余韻を大切に、締めすぎない。',
  },
  {
    id: 'anshin',
    name: '安心',
    category: 'emotion',
    trajectoryType: 'Type VI',
    description: '心配が静かに溶けていく、穏やかな安堵の感覚',
    dynamics: '脅威↓ B↑',
    coreRule: '心配から始め、それが静かに解消される。「あ、よかった」。派手にしない。',
  },
  // TENSION
  {
    id: 'suspense',
    name: 'サスペンス',
    category: 'tension',
    trajectoryType: 'Type V',
    description: '「次に何が起きるか」という問いが解消されないまま維持される緊張',
    dynamics: 'S維持 V↑ M↑',
    coreRule: '未解決のまま終わる。答えを与えない。「次は？」を宙吊りにする。',
  },
  {
    id: 'odoroki',
    name: '驚き',
    category: 'tension',
    trajectoryType: 'Type III',
    description: '予測されていなかった事実が突然出現する衝撃',
    dynamics: 'E↑↑↑ A↑',
    coreRule: 'インパクトの瞬間に切る。説明しない。読者に処理させる。',
  },
  {
    id: 'yosougai',
    name: '予想外の展開',
    category: 'tension',
    trajectoryType: 'Type II',
    description: '期待を設定し、その真逆か斜め上で回収する驚きと納得',
    dynamics: 'E↑↑ C遅 V↑',
    coreRule: '前半で期待を誘導し、後半で意味を再構成する。',
  },
  {
    id: 'kowai_chinmoku',
    name: '怖い沈黙',
    category: 'tension',
    trajectoryType: 'Type V',
    description: '何かがおかしいと感じるが、それが何かわからない不気味な静寂',
    dynamics: 'S_threat↑ S_social↑ B↓',
    coreRule: '何かが間違っているが明言しない。空気が凍ったまま終わる。',
  },
  // INTERACTION
  {
    id: 'conv_pleasure',
    name: '会話の気持ちよさ',
    category: 'interaction',
    trajectoryType: 'Type VII',
    description: '小さな相互理解が積み重なり、会話そのものが心地よくなる感覚',
    dynamics: 'R↑↑ 小ΔS×多',
    coreRule: '短い応酬の連続。オチなし。互いに理解し合っている感じ。自然な流れ。',
  },
  {
    id: 'nori',
    name: 'ノリの良さ',
    category: 'interaction',
    trajectoryType: 'Type VII',
    description: '共鳴するテンポが加速し、一体感が生まれる高揚感',
    dynamics: 'R↑↑↑ A↑',
    coreRule: '1行を短く。テンポ最優先。熟考しない。共有された勢い。',
  },
  {
    id: 'tempo_warui',
    name: 'テンポの悪さ',
    category: 'interaction',
    trajectoryType: 'Type IX',
    description: 'リズムのズレが積み重なり、会話がかみ合わない居心地の悪さ',
    dynamics: 'R↓ 噛み合わず',
    coreRule: '意図的にリズムを外す。間・曖昧さ・噛み合わなさ。悪者なし、ただすれ違う。',
  },
  {
    id: 'kimazui',
    name: '気まずさ',
    category: 'interaction',
    trajectoryType: 'Type V',
    description: '誰かが暗黙の境界線を越え、空気が固まる感覚',
    dynamics: 'S_social↑ B不確実',
    coreRule: '誰かが踏み越えてはいけない線を踏む。解決しない。凍った空気で終わる。',
  },
  {
    id: 'yoi_chinmoku',
    name: '心地よい沈黙',
    category: 'interaction',
    trajectoryType: 'Type VIII',
    description: '何も言わなくていい関係。沈黙が信頼の証になる',
    dynamics: 'R↑ B↑↑ demand↓',
    coreRule: '二人の存在感、言葉の必要のなさ。沈黙が安心に変わる。',
  },
  // STABLE
  {
    id: 'taikutsu',
    name: '退屈',
    category: 'stable',
    trajectoryType: 'Type VIII',
    description: '変化のない時間が引き伸ばされ、「で？」という感覚が生まれる',
    dynamics: 'E↓ V↓ 変化乏しい',
    coreRule: '意図的に静的。時間が伸びる感覚。「で？」という反応を目指す。',
  },
  {
    id: 'yoi_anshin',
    name: '予想通りの安心感',
    category: 'stable',
    trajectoryType: 'Type VIII',
    description: '変わらないものが変わらないことで、価値が保存される安心',
    dynamics: 'C↑ B↑ 価値保存',
    coreRule: '慣れ親しんだ場所・食べ物・儀式の繰り返し。変化なし。不変の肯定。',
  },
]

export const CATEGORY_LABELS: Record<string, string> = {
  humor: '笑い・面白さ',
  emotion: '感情の揺れ',
  tension: '緊張・スリル',
  interaction: '会話・対人',
  stable: '安定・予測',
}

export function getPattern(id: string): EmotionalPattern | undefined {
  return PATTERNS.find((p) => p.id === id)
}
